services:
  - type: web
    name: bandcamp-mcp
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.server_remote
